<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/LinearR_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1,20],[1,21],[1,22]]
y=[[210],[220],[230]]

In [0]:
Theta=[[0],[0]]

In [0]:
import numpy as np

In [0]:
alpha=0.002

In [0]:
X=np.array(data)
y=np.array(y)
Theta=np.array(Theta)

In [0]:
for i in range(10000):
  pred=np.matmul(X,Theta)
  cost=sum((y-pred)**2)
  Theta[0]=Theta[0]-alpha*sum((-2/len(X))*(y-pred))
  Theta[1]=Theta[1]-alpha*sum((-2/len(X))*(y-pred)*X[:,1].reshape(-1,1))
  print(cost,Theta)

[145400] [[ 0]
 [18]]
[75020] [[0]
 [4]]
[55560] [[ 0]
 [15]]
[27125] [[0]
 [7]]
[16005] [[ 0]
 [13]]
[8445] [[0]
 [8]]
[8120] [[ 0]
 [12]]
[3080] [[0]
 [9]]
[2885] [[ 0]
 [11]]
[365] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300] [[ 0]
 [10]]
[300]

In [0]:
np.matmul(X,Theta)

array([[200],
       [210],
       [220]])

In [0]:
Theta[1]

array([10])

In [0]:
(-2/len(X))*(y-pred)

array([[-6.66666667],
       [-6.66666667],
       [-6.66666667]])

In [0]:
Theta[1]

array([10])