<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/LinearR_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1,20],[1,21],[1,22]]
y=[[210],[220],[230]]

In [0]:
Theta=[[0.0],[0.0]]

In [0]:
import numpy as np

In [0]:
alpha=0.002

In [0]:
X=np.array(data)
y=np.array(y)
Theta=np.array(Theta)

In [66]:
for i in range(10000000):
  pred=np.matmul(X,Theta)
  cost=sum((y-pred)**2)
  Theta[0]=Theta[0]-alpha*sum((-2/len(X))*(y-pred))
  Theta[1]=Theta[1]-alpha*sum((-2/len(X))*(y-pred)*X[:,1].reshape(-1,1))
  if(i%1000000==0):
    print(cost,Theta)

[145400.] [[ 0.88      ]
 [18.50666667]]
[2.39421714e-06] [[ 9.97700616]
 [10.0010933 ]]
[1.40173635e-11] [[ 9.99994436]
 [10.00000265]]
[8.20668823e-17] [[ 9.99999987]
 [10.00000001]]
[5.40616652e-22] [[10.]
 [10.]]
[1.03146353e-22] [[10.]
 [10.]]
[1.03146353e-22] [[10.]
 [10.]]
[1.03146353e-22] [[10.]
 [10.]]
[1.03146353e-22] [[10.]
 [10.]]
[1.03146353e-22] [[10.]
 [10.]]


In [67]:
(y-pred)

array([[ 7.38964445e-12],
       [ 2.27373675e-13],
       [-6.96331881e-12]])

In [68]:
pred=np.matmul(X,Theta)
pred

array([[210.],
       [220.],
       [230.]])

In [8]:
Theta[0]=Theta[0]-alpha*sum((-2/len(X))*(y-pred))
Theta[0]

array([0])

In [9]:
Theta[1]=Theta[1]-alpha*sum((-2/len(X))*(y-pred)*X[:,1].reshape(-1,1))
Theta[1]

array([10])

In [0]:
Theta[0]=Theta[0]-alpha*sum((-2/len(X))*(y-pred))

In [0]:
Theta[0]=[0.44]

In [12]:
Theta[0]

array([0])