<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0]]
y=[[1.0],[0.0],[1.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [62]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
alpha=0.0005
ITheta=np.random.rand(X.shape[1],2).reshape(-1,2)
ETheta=np.random.rand(X.shape[1]).reshape(-1,1)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(1000000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  pred=1/(1+(np.exp(-1*np.matmul(Ipred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
  if(i%100000==0):
    print(cost)

[0.92698595]
[0.40554226]
[0.29231237]
[0.22473269]
[0.17997996]
[0.14873368]
[0.12599077]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


[0.10885364]
[0.09556107]
[0.08499692]


In [52]:
ITheta[0]=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)

ValueError: ignored

In [37]:
ITheta=ITheta-sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)

array([[-0.22200045, -0.22200045],
       [-4.68238373, -4.68238373],
       [ 0.06171753,  0.06171753]])

In [28]:
ITheta

array([[0.001, 0.001],
       [0.001, 0.001],
       [0.001, 0.001]])

In [63]:
pred

array([[0.89330147],
       [0.10992567],
       [0.99999996]])

In [31]:
a[:,1].reshape(-1,1)

array([[2],
       [4],
       [6]])

In [0]:
sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)

array([[0.43197927],
       [0.21906421],
       [0.21906421]])

In [0]:
np.random.rand(X.shape[1]).reshape(-1,1)

array([[0.7343088 ],
       [0.0127714 ],
       [0.43010706]])