<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0]]
y=[[1.0],[0.0],[1.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [244]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
alpha=2.5
ITheta=np.ones((X.shape[1],2)).reshape(-1,2)*0.001
ETheta=np.random.rand(X.shape[1]).reshape(-1,1)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(2000000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  pred=1/(1+(np.exp(-1*np.matmul(Ipred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  if(i%200000==0):
    print(cost)

[0.66679196]
[0.5076898]
[0.45022365]
[0.41812365]
[0.39701881]
[0.38151123]
[0.36921596]
[0.35893615]
[0.35000986]
[0.34204263]


In [194]:
ETheta

array([[0.],
       [0.],
       [0.]])

In [245]:
pred

array([[0.611682  ],
       [0.39640082],
       [0.99206324]])

In [234]:
Ipred

array([[1.        , 0.50824925, 0.50824925],
       [1.        , 0.50774938, 0.50774938],
       [1.        , 0.51074834, 0.51074834]])

In [203]:
sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred)

array([-172.17094523,  -87.31034387,  -87.31034387])

In [201]:
2*(pred-y)*(np.matmul(Ipred,ETheta))

array([[-0.],
       [ 0.],
       [-0.]])

In [204]:
sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)

array([[0.43197927],
       [0.21906421],
       [0.21906421]])

In [242]:
np.random.rand(X.shape[1]).reshape(-1,1)

array([[0.7343088 ],
       [0.0127714 ],
       [0.43010706]])