<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [205]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.003

#ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(num_hlayers,num_hunits+1,num_hunits)
ETheta=np.random.rand(num_hunits+1,num_eunits).reshape(-1,num_eunits)
Hpred1=np.ones((num_hlayers,X.shape[0],num_hunits))
Hpred=np.ones((num_hlayers,X.shape[0],num_hunits+1))
#print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(20000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1[0]=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta[0]))))
  Hpred[0]=np.c_[np.ones((len(X),1)),Hpred1[0]]
  for j in range(num_hlayers-1):
    Hpred1[j+1]=1/(1+(np.exp(-1*np.matmul(Hpred[j],HTheta[j+1]))))
    Hpred[j+1]=np.c_[np.ones((len(X),1)),Hpred1[j+1]]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred[num_hlayers-1],ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
  HTheta[0]=HTheta[0]-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1[0]))
  for k in range(num_hlayers-1):
    HTheta[k+1]=HTheta[k+1]-alpha*(sum((-2/len(Hpred[k]))*(y-pred)*Hpred[k]).reshape(-1,1)*sum(Hpred1[k+1]))
  ETheta=ETheta-alpha*sum((-2/len(Hpred[num_hlayers-1]))*(y-pred)*Hpred[num_hlayers-1]).reshape(-1,1)

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%2000==0):
    print(cost)

[0.77513991]
[0.56099322]
[0.4268202]
[0.33454213]
[0.27178474]
[0.2274441]
[0.19484493]
[0.17004255]
[0.15062688]
[0.13506405]


In [206]:
pred

array([[0.79126661],
       [0.11921864],
       [0.99863138],
       [0.11921864]])

array([[0.84123681, 0.27506182],
       [0.27320508, 0.46180242]])

In [93]:
HTheta

array([[[0.2767468 , 0.55064456, 0.65754802],
        [0.21431419, 0.45529122, 0.27711789],
        [0.1615788 , 0.83642444, 0.41072138],
        [0.19906781, 0.07610002, 0.42633604]]])

In [94]:
i

1

In [70]:
Hpred

array([[1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833]])

In [0]:
Ht=np.ones((num_hlayers,num_hunits+1,num_hunits))

In [62]:
Ht

array([[[-3.31610722, -3.30564839, -3.30358725],
        [ 6.30420464,  6.42023446,  5.65192502],
        [ 4.74558641,  5.01465938,  4.75467511],
        [ 0.78897396,  0.86937907,  0.02893208]],

       [[ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ]]])

In [0]:
Ht[0]=HTheta