<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [98]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=3
num_eunits=1
num_hlayers=2
alpha=0.005

#ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(num_hlayers,num_hunits+1,num_hunits)
ETheta=np.random.rand(num_hunits+1,num_eunits).reshape(-1,num_eunits)
Hpred1=np.ones((num_hlayers,X.shape[0],num_hunits))
Hpred=np.ones((num_hlayers,X.shape[0],num_hunits+1))
print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(10000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  for j in range(num_hlayers):
    Hpred1[j]=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta[j]))))
    Hpred[j]=np.c_[np.ones((len(X),1)),Hpred1[j]]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred[num_hlayers-1],ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
  HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1[num_hlayers-1]))
  ETheta=ETheta-alpha*sum((-2/len(Hpred[num_hlayers-1]))*(y-pred)*Hpred[num_hlayers-1]).reshape(-1,1)

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%1000==0):
    print(cost)

[[0.36272836]
 [0.54322682]
 [0.80692714]
 [0.45293141]] [[0.55645782 0.37461747 0.51653769]
 [0.66605856 0.15917824 0.92368356]
 [0.93280702 0.02360255 0.73823142]] [[[0.00781046 0.88724871 0.42688681]
  [0.2192018  0.16410845 0.54691275]
  [0.59668805 0.41843806 0.7807491 ]
  [0.29907438 0.59638376 0.37494612]]

 [[0.32681967 0.96812946 0.59520325]
  [0.05755753 0.97412103 0.26586079]
  [0.30008559 0.29459006 0.83546815]
  [0.99545858 0.42219844 0.62509474]]]
[1.12135931]
[0.63389226]
[0.4925359]
[0.40496811]
[0.3371706]
[0.28561927]
[0.24597075]
[0.21495055]
[0.19024751]
[0.17024354]


In [99]:
y-pred

array([[ 0.25740068],
       [-0.14646467],
       [ 0.00090419],
       [-0.1464656 ]])

In [0]:
HTheta=np.random.rand(num_hlayers,num_hunits+1,num_hunits)

In [93]:
HTheta

array([[[0.2767468 , 0.55064456, 0.65754802],
        [0.21431419, 0.45529122, 0.27711789],
        [0.1615788 , 0.83642444, 0.41072138],
        [0.19906781, 0.07610002, 0.42633604]]])

In [94]:
i

1

In [70]:
Hpred

array([[1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833],
       [1.        , 0.88771067, 0.8243774 , 0.66388833]])

In [0]:
Ht=np.ones((num_hlayers,num_hunits+1,num_hunits))

In [62]:
Ht

array([[[-3.31610722, -3.30564839, -3.30358725],
        [ 6.30420464,  6.42023446,  5.65192502],
        [ 4.74558641,  5.01465938,  4.75467511],
        [ 0.78897396,  0.86937907,  0.02893208]],

       [[ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ]]])

In [0]:
Ht[0]=HTheta