<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [21]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.0005
Ipred=np.ones((X.shape[0],num_hunits+1))
ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
HTheta=np.random.rand(Ipred.shape[1],num_hunits).reshape(-1,num_hunits)
print(ETheta,ITheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(10000000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
  Hpred=np.c_[np.ones((len(X),1)),Hpred1]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
  if(i%1000000==0):
    print(cost)

[[0.28231872]
 [0.18952636]
 [0.9260682 ]] [[0.66635421 0.91919308]
 [0.72030669 0.66138201]
 [0.83170144 0.99990293]]
[0.87478691]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


[0.26756947]
[0.17990639]
[0.1325196]
[0.10371894]
[0.08468416]
[0.07129487]
[0.06142069]
[0.05386623]
[0.04791513]


In [22]:
pred

array([[0.92162214],
       [0.04440326],
       [1.        ],
       [0.04440326]])

In [9]:
Ipred

array([[1.00000000e+000, 6.47254871e-007, 5.08474995e-001],
       [1.00000000e+000, 5.82199467e-102, 2.10553290e-096],
       [1.00000000e+000, 1.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 1.00391742e-132, 1.76674017e-128]])

In [11]:
print(X.shape[0],num_hunits+1)

4 3


In [8]:
np.random.rand(X.shape[1]).reshape(-1,1)

array([[0.31656609],
       [0.70762069],
       [0.03863844]])