<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [58]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.5

#ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(1000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
  Hpred=np.c_[np.ones((len(X),1)),Hpred1]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
  HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Ipred1))
  ETheta=ETheta-alpha*(sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)*sum(Hpred1))

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%100==0):
    print(cost)

[[0.92194583]
 [0.6880842 ]
 [0.82325485]] [[0.39957969 0.86301476]
 [0.13384569 0.06232557]
 [0.190013   0.20506494]] [[0.01058471 0.88366951]
 [0.69536196 0.68951949]
 [0.11391282 0.61340061]]
[1.17948376]


ValueError: ignored

In [22]:
pred

array([[0.99856475],
       [0.01234649],
       [0.99856475],
       [0.01234649]])

In [23]:
print(ETheta,ITheta,HTheta)

[[-4.51175277]
 [ 5.87671212]
 [ 5.17587941]] [[ -4.37555618  -4.8626009 ]
 [-78.14762127 -78.10798215]
 [131.05299718 130.79736491]] [[-4.58375888 -4.37647021]
 [ 8.95599095  9.65989446]
 [ 8.50356562  8.50003435]]


In [66]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.5

#ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
Ipred=np.c_[np.ones((len(X),1)),Ipred1]
Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
Hpred=np.c_[np.ones((len(X),1)),Hpred1]
pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
#HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Ipred1))
#ETheta=ETheta-alpha*(sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)*sum(Hpred1))

[[0.13171082]
 [0.37963954]
 [0.34410786]] [[0.68847644 0.82806796]
 [0.00281773 0.82331282]
 [0.03816536 0.25563342]] [[0.69931632 0.73559786]
 [0.99800209 0.05316395]
 [0.5955427  0.54081772]]


In [35]:
ITheta

array([[ -4.31443938,  -5.05317838],
       [-75.74247984, -75.67780001],
       [129.08350174, 129.06774948]])

In [47]:
ITheta*I

array([[  -8.62887877,  -15.15953513],
       [-151.48495967, -227.03340002],
       [ 258.16700348,  387.20324844]])

In [67]:
print(ETheta,ITheta,HTheta)

[[0.13171082]
 [0.37963954]
 [0.34410786]] [[ 0.51153109  0.65112262]
 [-3.20571225 -2.38521716]
 [ 0.0824337   0.29990176]] [[0.69931632 0.73559786]
 [0.99800209 0.05316395]
 [0.5955427  0.54081772]]


In [43]:
sum(Ipred1)

array([2., 2.])

In [64]:
(alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1))*I

array([[ 0.43894518,  0.65841777],
       [ 8.13866381, 12.20799571],
       [ 0.90767675,  1.36151512]])

In [0]:
HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Ipred1))