<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [104]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.001

#ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(100000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
  Hpred=np.c_[np.ones((len(X),1)),Hpred1]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
  HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1))
  ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%10000==0):
    print(cost)

[[0.08818259]
 [0.72135877]
 [0.49090276]] [[0.25064976 0.43856881]
 [0.37795809 0.94336052]
 [0.4740869  0.37529462]] [[0.39440627 0.36856974]
 [0.93160859 0.36278745]
 [0.59046114 0.52714616]]
[0.83716488]
[0.44025152]
[0.29531771]
[0.21751623]
[0.17079672]
[0.14008278]
[0.1185166]
[0.10261219]
[0.09043204]
[0.08082159]


In [105]:
pred

array([[0.87020136],
       [0.07365486],
       [0.99982991],
       [0.07365486]])

In [23]:
print(ETheta,ITheta,HTheta)

[[-4.51175277]
 [ 5.87671212]
 [ 5.17587941]] [[ -4.37555618  -4.8626009 ]
 [-78.14762127 -78.10798215]
 [131.05299718 130.79736491]] [[-4.58375888 -4.37647021]
 [ 8.95599095  9.65989446]
 [ 8.50356562  8.50003435]]


In [93]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.5

#ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
Ipred=np.c_[np.ones((len(X),1)),Ipred1]
Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
Hpred=np.c_[np.ones((len(X),1)),Hpred1]
pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1))
ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)

[[0.94435415]
 [0.62349965]
 [0.19064888]] [[0.00570089 0.20349214]
 [0.0157739  0.48534152]
 [0.44601919 0.57317976]] [[0.03740053 0.80065007]
 [0.26474903 0.8109223 ]
 [0.82886538 0.41308136]]


In [0]:
Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
Ipred=np.c_[np.ones((len(X),1)),Ipred1]
Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
Hpred=np.c_[np.ones((len(X),1)),Hpred1]
pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))

In [84]:
Hpred

array([[1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283]])

In [95]:
ETheta

array([[ 0.61467053],
       [ 0.37486989],
       [-0.09950996]])

In [67]:
print(ETheta,ITheta,HTheta)

[[0.13171082]
 [0.37963954]
 [0.34410786]] [[ 0.51153109  0.65112262]
 [-3.20571225 -2.38521716]
 [ 0.0824337   0.29990176]] [[0.69931632 0.73559786]
 [0.99800209 0.05316395]
 [0.5955427  0.54081772]]


In [43]:
sum(Ipred1)

array([2., 2.])

In [64]:
(alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1))*I

array([[ 0.43894518,  0.65841777],
       [ 8.13866381, 12.20799571],
       [ 0.90767675,  1.36151512]])

In [0]:
HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Ipred1))