<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [146]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.005

ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

#ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(10000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
  Hpred=np.c_[np.ones((len(X),1)),Hpred1]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
  HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1))
  ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%1000==0):
    print(cost)

[[1.]
 [1.]
 [1.]] [[1. 1.]
 [1. 1.]
 [1. 1.]] [[1. 1.]
 [1. 1.]
 [1. 1.]]
[1.50586906]
[0.69339317]
[0.56175297]
[0.45294819]
[0.36961716]
[0.30869218]
[0.26336754]
[0.22877226]
[0.20170331]
[0.18005197]


In [147]:
pred

array([[0.73249157],
       [0.15411208],
       [0.99638087],
       [0.15411208]])

In [124]:
print(ETheta,ITheta,HTheta)

[[-2.54059241]
 [ 5.56702384]
 [ 5.56702384]] [[ -2.00698422  -2.00698422]
 [-44.85580451 -44.85580451]
 [ 74.83918371  74.83918371]] [[-4.60602814 -4.60602814]
 [ 8.03320461  8.03320461]
 [ 8.03320461  8.03320461]]


In [93]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.5

#ITheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#HTheta=np.ones((X.shape[1],num_hunits)).reshape(-1,num_hunits)
#ETheta=np.ones((X.shape[1],num_eunits)).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
Ipred=np.c_[np.ones((len(X),1)),Ipred1]
Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
Hpred=np.c_[np.ones((len(X),1)),Hpred1]
pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1))
ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)

[[0.94435415]
 [0.62349965]
 [0.19064888]] [[0.00570089 0.20349214]
 [0.0157739  0.48534152]
 [0.44601919 0.57317976]] [[0.03740053 0.80065007]
 [0.26474903 0.8109223 ]
 [0.82886538 0.41308136]]


In [0]:
Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
Ipred=np.c_[np.ones((len(X),1)),Ipred1]
Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
Hpred=np.c_[np.ones((len(X),1)),Hpred1]
pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))

In [84]:
Hpred

array([[1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283],
       [1.        , 0.39166963, 0.41838283]])

In [95]:
ETheta

array([[ 0.61467053],
       [ 0.37486989],
       [-0.09950996]])

In [67]:
print(ETheta,ITheta,HTheta)

[[0.13171082]
 [0.37963954]
 [0.34410786]] [[ 0.51153109  0.65112262]
 [-3.20571225 -2.38521716]
 [ 0.0824337   0.29990176]] [[0.69931632 0.73559786]
 [0.99800209 0.05316395]
 [0.5955427  0.54081772]]


In [43]:
sum(Ipred1)

array([2., 2.])

In [64]:
(alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1))*I

array([[ 0.43894518,  0.65841777],
       [ 8.13866381, 12.20799571],
       [ 0.90767675,  1.36151512]])

In [0]:
HTheta=HTheta-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Ipred1))