<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0]]
y=[[1.0],[0.0],[1.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [173]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
alpha=2.5
ITheta=np.ones((X.shape[1],2)).reshape(-1,2)*0.001
ETheta=np.zeros((X.shape[1])).reshape(-1,1)
for i in range(10000000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  pred=1/(1+(np.exp(-1*np.matmul(Ipred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  if(i%1000000==0):
    print(cost)

[0.69314718]
[0.38153312]
[0.3347965]
[0.30485528]
[0.28077056]
[0.26011467]
[0.24199108]
[0.22592367]
[0.21159032]
[0.19874374]


In [147]:
ETheta

array([[5.74251168],
       [2.91862726],
       [2.91862726]])

In [174]:
pred

array([[0.75524322],
       [0.24484294],
       [0.99999584]])

In [129]:
Ipred

array([[1.        , 0.50824925, 0.50824925],
       [1.        , 0.50774938, 0.50774938],
       [1.        , 0.51074834, 0.51074834]])

In [88]:
alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)

array([[0.0004283 ],
       [0.00021418],
       [0.00021418]])