<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [27]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
alpha=0.0005
ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(100000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  pred=1/(1+(np.exp(-1*np.matmul(Ipred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
  if(i%10000==0):
    print(cost)

[[0.94448248]
 [0.25762697]
 [0.31231678]] [[0.68255608 0.04852794]
 [0.71074232 0.07522497]
 [0.57886386 0.97153396]]
[0.95596192]
[0.69393152]
[0.54944599]
[0.45194954]
[0.37363953]
[0.3163635]
[0.27312471]
[0.23959835]
[0.21297462]
[0.19138993]


In [28]:
pred

array([[0.71827891],
       [0.16371864],
       [0.99417886],
       [0.16371864]])

In [29]:
print(ETheta,ITheta)

[[-1.63082577]
 [ 4.99681866]
 [ 1.77445691]] [[ -1.89275218  -2.52678032]
 [-37.4653577  -38.10087505]
 [ 62.60453177  62.99720187]]


In [0]:
sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)

In [0]:
np.random.rand(X.shape[1]).reshape(-1,1)