<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
#data=[[1.0,20.0,12.0],[1.0,17.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [254]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=5
num_eunits=1
num_hlayers=1
alpha=0.001

#ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#HTheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
#ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)

ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(num_hlayers,num_hunits+1,num_hunits)
ETheta=np.random.rand(num_hunits+1,num_eunits).reshape(-1,num_eunits)
Hpred1=np.ones((num_hlayers,X.shape[0],num_hunits))
Hpred=np.ones((num_hlayers,X.shape[0],num_hunits+1))
#print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(20000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1[0]=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta[0]))))
  Hpred[0]=np.c_[np.ones((len(X),1)),Hpred1[0]]
  for j in range(num_hlayers-1):
    Hpred1[j+1]=1/(1+(np.exp(-1*np.matmul(Hpred[j],HTheta[j+1]))))
    Hpred[j+1]=np.c_[np.ones((len(X),1)),Hpred1[j+1]]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred[num_hlayers-1],ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  
  ITheta=ITheta-alpha*(sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)*sum(Ipred1))
  HTheta[0]=HTheta[0]-alpha*(sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)*sum(Hpred1[0]))
  for k in range(num_hlayers-1):
    HTheta[k+1]=HTheta[k+1]-alpha*(sum((-2/len(Hpred[k]))*(y-pred)*Hpred[k]).reshape(-1,1)*sum(Hpred1[k+1]))
    #HTheta[k+1]=HTheta[k+1]-alpha*(sum((-2/len(Hpred[k]))*(y-pred)*Hpred[k]).reshape(-1,1))
  ETheta=ETheta-alpha*sum((-2/len(Hpred[num_hlayers-1]))*(y-pred)*Hpred[num_hlayers-1]).reshape(-1,1)

  #ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #HTheta=HTheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  #ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  
  if(i%2000==0):
    print(cost)

[1.55116525]
[0.69664204]
[0.69296704]
[0.57971602]
[0.53198197]
[0.50411876]
[0.46825115]
[0.43430559]
[0.40406803]
[0.37678104]


In [255]:
pred

array([[0.50261595],
       [0.29549535],
       [0.98052067],
       [0.29559396]])

In [238]:
HTheta

array([[[-0.7397082 , -0.64328719, -0.56829303, -0.53259845,
         -0.3386241 , -0.37075677, -0.33517619, -0.59156363,
         -0.32947181, -0.48518336],
        [ 0.71151545,  1.19821467,  0.98815836,  0.37528854,
          1.08766691,  0.89824214,  0.50530888,  1.14781104,
          0.44301327,  0.38507656],
        [ 1.48051565,  0.61373788,  1.09055391,  1.49499454,
          1.50375992,  1.54528899,  1.23037677,  0.70726596,
          0.90204968,  1.01003359],
        [ 0.55202508,  0.51516961,  1.1220638 ,  1.17231909,
          0.79987172,  0.65262573,  0.42181371,  0.4052417 ,
          0.4075319 ,  1.32064014],
        [ 1.07755721,  0.69681316,  1.30822566,  1.34650791,
          1.3686752 ,  0.71459401,  1.07834616,  0.71365577,
          0.62837942,  1.11008431],
        [ 0.91257284,  0.83667897,  1.1393908 ,  0.83306885,
          1.05143199,  0.46636882,  0.44365295,  0.56160685,
          0.33383163,  0.9985915 ],
        [ 0.77683036,  0.93030555,  0.56452355,  1.5

In [239]:
i

19999

In [240]:
Hpred

array([[[1.        , 0.99988371, 0.99979048, 0.99998038, 0.99991014,
         0.99996866, 0.99984678, 0.99934373, 0.99782832, 0.99926792,
         0.99983832],
        [1.        , 0.99988371, 0.99979048, 0.99998038, 0.99991014,
         0.99996866, 0.99984678, 0.99934373, 0.99782832, 0.99926792,
         0.99983832],
        [1.        , 0.99988371, 0.99979048, 0.99998038, 0.99991014,
         0.99996866, 0.99984678, 0.99934373, 0.99782832, 0.99926792,
         0.99983832],
        [1.        , 0.99988371, 0.99979048, 0.99998038, 0.99991014,
         0.99996866, 0.99984678, 0.99934373, 0.99782832, 0.99926792,
         0.99983832]],

       [[1.        , 0.05576612, 0.08588107, 0.13008513, 0.03297426,
         0.04277825, 0.09000183, 0.07055045, 0.03313074, 0.05557111,
         0.05928851],
        [1.        , 0.05576612, 0.08588107, 0.13008513, 0.03297426,
         0.04277825, 0.09000183, 0.07055045, 0.03313074, 0.05557111,
         0.05928851],
        [1.        , 0.05576612, 0.085

In [0]:
Ht=np.ones((num_hlayers,num_hunits+1,num_hunits))

In [242]:
Ht

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [243]:
Ht[0]=HTheta

ValueError: ignored