<a href="https://colab.research.google.com/github/venkat2ram/ML_From_Scratch/blob/master/NeuralNet_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data=[[1.0,20.0,12.0],[1.0,21.0,9.0],[1.0,22.0,20.0],[1.0,18.0,6.0]]
y=[[1.0],[0.0],[1.0],[0.0]]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
X=np.array(data)
y=np.array(y)

In [32]:
plot_cost=np.array([[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0],[0.0,0.0]])
j=0
num_hunits=2
num_eunits=1
num_hlayers=1
alpha=0.0001
Ipred=np.ones((X.shape[0],num_hunits+1))
ITheta=np.random.rand(X.shape[1],num_hunits).reshape(-1,num_hunits)
HTheta=np.random.rand(Ipred.shape[1],num_hunits).reshape(-1,num_hunits)
ETheta=np.random.rand(X.shape[1],num_eunits).reshape(-1,num_eunits)
print(ETheta,ITheta,HTheta)
#ETheta=np.ones((X.shape[1])).reshape(-1,1)
for i in range(1000000):
  Ipred1=1/(1+(np.exp(-1*np.matmul(X,ITheta))))
  Ipred=np.c_[np.ones((len(X),1)),Ipred1]
  Hpred1=1/(1+(np.exp(-1*np.matmul(Ipred,HTheta))))
  Hpred=np.c_[np.ones((len(X),1)),Hpred1]
  pred=1/(1+(np.exp(-1*np.matmul(Hpred,ETheta))))
  cost=sum((-1/len(X))*(y*np.log(pred)+(1-y)*np.log(1-pred)))
  ETheta=ETheta-alpha*sum((-2/len(Hpred))*(y-pred)*Hpred).reshape(-1,1)
  HTheta=HTheta-alpha*sum((-2/len(Ipred))*(y-pred)*Ipred).reshape(-1,1)
  #ETheta=ETheta+alpha*sum(2*(pred-y)*(np.matmul(Ipred,ETheta))*(1-(np.matmul(Ipred,ETheta)))*Ipred).reshape(-1,1)
  ITheta=ITheta-alpha*sum((-2/len(Ipred))*(y-pred)*X).reshape(-1,1)
  if(i%100000==0):
    print(cost)

[[0.17361311]
 [0.11958437]
 [0.59512856]] [[0.99001824 0.65539312]
 [0.96801457 0.29389359]
 [0.39059805 0.4698506 ]] [[0.16207866 0.24375323]
 [0.45195834 0.65394161]
 [0.29891561 0.65746527]]
[0.76192679]
[0.50909614]
[0.35737348]
[0.26160422]
[0.20134909]
[0.16138494]
[0.13351082]
[0.11323667]
[0.09797013]
[0.0861375]


In [33]:
pred

array([[0.86413298],
       [0.07717998],
       [0.99970594],
       [0.07717998]])

In [34]:
print(ETheta,ITheta,HTheta)

[[-3.01793589]
 [ 5.15348057]
 [ 5.99915608]] [[ -2.20153076  -2.53615588]
 [-46.74319985 -47.41732083]
 [ 78.03363448  78.11288703]] [[-3.02947034 -2.94779577]
 [ 7.91268987  8.11467314]
 [ 2.96232297  3.32087264]]


In [11]:
print(X.shape[0],num_hunits+1)

4 3


In [8]:
np.random.rand(X.shape[1]).reshape(-1,1)

array([[0.31656609],
       [0.70762069],
       [0.03863844]])